In [1]:
import numpy as np

# 1. Create a 3x3x3 array with random values 

In [11]:
a=np.random.random((3,3))

In [3]:
a


array([[-1.54102003, -0.71014037, -1.59411626],
       [-0.19699939, -0.81887518, -0.65929015],
       [ 1.00214654, -1.88139162,  1.60804447]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [12]:


x = np.zeros((8,8))

x[1::2,::2] = 1

x[::2,1::2] = 1
print(x)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 4. Normalize a 5x5 random matrix

In [13]:
x= np.random.random((3,3))

xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)

print(x)

[[0.         0.52468555 0.99853811]
 [0.8224762  0.03346976 0.26830967]
 [0.50641273 0.7802414  1.        ]]


# 5.  How to find common values between two arrays?

In [16]:
a=np.array([1,2,3])
b=np.array([2,4,5])
print(np.intersect1d(a,b))

[2]


# 6.How to get the dates of yesterday, today and tomorrow?

In [17]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-31
Today:  2020-08-01
Tomorrow:  2020-08-02


# 7. Consider two random array A and B, check if they are equal

In [21]:
a=np.random.random((2,2))
b=np.random.random((2,2))
print((a==b).all())

False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [28]:
a=np.random.random(10)
print(a)
a[a.argmax()]=0
a

[0.2045204  0.80901076 0.94420423 0.89080086 0.42328792 0.87418947
 0.46100038 0.29229322 0.72306277 0.42042534]


array([0.2045204 , 0.80901076, 0.        , 0.89080086, 0.42328792,
       0.87418947, 0.46100038, 0.29229322, 0.72306277, 0.42042534])

# 9. How to print all the values of an array?

In [32]:
np.set_printoptions()
x = np.zeros((4, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [39]:

a=np.random.random((3,3))
print(a)
b=a-a.mean(axis=1)
b

[[0.20811763 0.52356149 0.2775463 ]
 [0.23158165 0.88223987 0.91147274]
 [0.86953323 0.95827608 0.15442523]]


array([[-0.12829084, -0.1515366 , -0.38319855],
       [-0.10482682,  0.20714179,  0.25072789],
       [ 0.53312476,  0.28317799, -0.50631962]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [40]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


# 12.How to get the diagonal of a dot product?

In [43]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))
np.diag(np.dot(A, B))

array([ 77,  10, 101])

# 13.How to find the most frequent value in an array?

In [50]:
x = np.random.randint(0, 10, 10)
from statistics import mode

print(mode(x))

5


# 14.How to get the n largest values of an array

In [51]:
import numpy as np
x = np.arange(10)

np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


# 15.How to create a record array from a regular array?

In [52]:
import numpy as np
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])

(1, 'Red', 12.2)
(2, 'Green', 15.)
(3, 'White', 20.)
